### GENERAL SETTINGS ###

# Site settings
title: FLOSS for Science
description: "Podcasts about Free/Libre and Open Source Software (FLOSS) for Science"
baseurl: "" #important: start with /
url: "https://flossforscience.github.io"
future: false
# Google Analytics
google_analytics: UA-112467064-1

# Build settings
markdown: kramdown
permalink: /podcast/:title
excerpt_separator: <!--more--> #use this in posts to define how long the excerpt of the post (that is shown on the Blog page) is

colors:  #in hex code if not noted else
  primary: "#f6830ff0" #"#f6830ff0"
  primary_rgb: "246,131,15" #"247,0,49" #rgb of the primary. Needed in some places for the transparency effect.
  secondary: "#384452" #"#33004D"
  link: "#428bca"
  link_hover: "#01b2fe"
  footer_heading: "#ffffff"
  footer_content: "#bfc9d3"

# Making projects separate from posts
collections:
  projects:
    output: true
    permalink: /projects/:title/
  questions:
    output: true
    permalink: /questions/:title/

### CONTACT SETTINGS ###

# Social networks usernames. Many more available: google-plus, flickr, linkedin, etc). Shown in footer.
social:
#  - title: dribbble
#    url:
#  - title: facebook
#    url:
   - title: twitter
     url: https://twitter.com/FLOSSforscience
     name: FLOSSforscience
   - title: github
     url: https://github.com/FLOSSforScience
     name: FLOSSforscience
#  - title: instagram
#    url:
#  - title: tumblr
#    url:

# Postal address (add as many lines as necessary). Shown in footer and on Contact page.
address:
  - lines:
    - Montreal, Canada
email: flossforscience@gmail.com
tel: 



### GENERAL DATA FOR VARIOUS LOCATIONS ###

# Members information. Shown on About page.
#members:
#  - name: Mark Webber
#    position: CEO
#    text: Lorem Ipsum is simply dummy text of the printing and typesetting industry.
#    img: team01.jpg
#    social:
#      - title: envelope #use for email address
#        url: mailto:name@domain.com
#      - title: twitter
#        url: http://twitter.com/handle


# Clients information. Shown on Home and About pages.
#clients:
#  - name: dribbble
#    img: client01.png

# Short text about your company. Shown in footer on every page and also separately on Home and Contact page.
about: "Podcasts about Free/Libre and Open Source Software (FLOSS) for Science"

# Testimonial content. Shown on Home and About page.
#testimonial:
#    message: "Our mission statement goes here"
#    author: 
#    position: 

#Configuration for the rss feed to handle podcasts
podcast_url: https://flossforscience.github.io/
podcast_album_art: https://raw.githubusercontent.com/FLOSSforScience/FLOSSforScience.github.io/master/assets/img/logo.png
# podcast_album_art: /assets/img/logo.png
podcast_title: Free and Libre Open Source Software for Science
podcast_owner: FLOSSforScience
podcast_email: flossforscience@gmail.com 
podcast_category: Technology
podcast_subcategory_one: Software How-To
podcast_subcategory_two: Podcasting
podcast_explicit: "no"
podcast_author: FLOSSforScience
podcast_description: Open Source software in Science
podcast_summary: Interviews with scientists who are using or developing free and libre open source software

plugins:
  - jekyll-seo-tag
